# For more info on HTTP files go to https://aka.ms/vs/httpfile
https://pdaapimqa.royalmailgroup.net/updaterouteservice/v1/UpdatedRoutes?fromDate=2024-07-17&toDate=2025-07-20
X-RMG-CLIENT-ID:973fd29c-08c2-4f0a-a974-80188c9da8b1 
Accept: application/json 
